<?xml version="1.0"?>
<Procedure Version="5" type="954B999B">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
        <Input id="2" type="Integer" name="#" description=""/>
    </Inputs>
    <Constants/>
    <Operators>
        <Operator id="1" type="954B5E2E"/>
        <Operator id="2" type="C26F5E4E">
            <Connect in="1" input="1"/>
            <Connect in="2" to="1" out="1"/>
            <Connect in="3" input="2"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="" description="" to="2" out="1"/>
    </Outputs>
</Procedure>
