<?xml version="1.0"?>
<Procedure Version="5" type="FA9719BA">
    <Inputs>
        <Input id="1" type="Frame" name="Frame" description=""/>
        <Input id="2" type="Integer" name="Select" description="|Min=0|Max=7"/>
    </Inputs>
    <Constants>
        <Constant id="-34" type="ModelSegment"></Constant>
        <Constant id="-37" type="String">Box</Constant>
        <Constant id="-39" type="List"></Constant>
        <Constant id="-42" type="Float">0.000000</Constant>
        <Constant id="-43" type="Integer">0</Constant>
        <Constant id="-44" type="Integer">2</Constant>
        <Constant id="-45" type="Bool">False</Constant>
        <Constant id="-48" type="ModelSegment"></Constant>
        <Constant id="-54" type="Vector3">1.000000, 1.000000, 0.000000</Constant>
        <Constant id="-62" type="ModelSegment"></Constant>
        <Constant id="-67" type="Integer">15</Constant>
        <Constant id="-74" type="Float">0.333000</Constant>
        <Constant id="-75" type="Bool">True</Constant>
        <Constant id="-77" type="Float">0.333000</Constant>
        <Constant id="-78" type="Bool">True</Constant>
        <Constant id="-95" type="ModelSegment"></Constant>
        <Constant id="-96" type="ModelSegment"></Constant>
        <Constant id="-97" type="Float">0.333000</Constant>
        <Constant id="-98" type="Bool">True</Constant>
        <Constant id="-101" type="Float">0.333000</Constant>
        <Constant id="-102" type="Bool">True</Constant>
        <Constant id="-107" type="Integer">16</Constant>
        <Constant id="-110" type="Integer">0</Constant>
        <Constant id="-112" type="ModelSegment"></Constant>
        <Constant id="-117" type="Integer">2</Constant>
        <Constant id="-121" type="Bool">True</Constant>
        <Constant id="-122" type="Bool">True</Constant>
        <Constant id="-123" type="Integer">1</Constant>
        <Constant id="-124" type="Bool">True</Constant>
        <Constant id="-125" type="Integer">3</Constant>
        <Constant id="-126" type="Bool">True</Constant>
        <Constant id="-127" type="Integer">0</Constant>
        <Constant id="-128" type="Integer">1</Constant>
        <Constant id="-129" type="Integer">2</Constant>
        <Constant id="-130" type="Integer">3</Constant>
        <Constant id="-134" type="Bool">False</Constant>
        <Constant id="-135" type="Bool">False</Constant>
        <Constant id="-136" type="Bool">False</Constant>
        <Constant id="-137" type="Bool">False</Constant>
        <Constant id="-138" type="Bool">False</Constant>
        <Constant id="-139" type="Bool">False</Constant>
        <Constant id="-140" type="Bool">False</Constant>
        <Constant id="-141" type="Bool">False</Constant>
        <Constant id="-142" type="Bool">False</Constant>
        <Constant id="-143" type="Bool">False</Constant>
        <Constant id="-144" type="Bool">False</Constant>
        <Constant id="-145" type="Float">0.000000</Constant>
        <Constant id="-146" type="Float">0.000000</Constant>
        <Constant id="-147" type="Integer">0</Constant>
        <Constant id="-148" type="Integer">0</Constant>
        <Constant id="-149" type="Integer">0</Constant>
        <Constant id="-150" type="Integer">0</Constant>
        <Constant id="-151" type="Integer">0</Constant>
        <Constant id="-152" type="Integer">0</Constant>
        <Constant id="-153" type="Integer">0</Constant>
        <Constant id="-154" type="Integer">0</Constant>
        <Constant id="-155" type="Integer">0</Constant>
        <Constant id="-156" type="Integer">0</Constant>
        <Constant id="-157" type="Integer">0</Constant>
        <Constant id="-158" type="Integer">0</Constant>
    </Constants>
    <Operators>
        <Operator id="10" type="88B7A911">
            <Connect in="100" to="32" out="1"/>
            <Connect in="101" constant="-34"/>
            <Connect in="102" to="13" out="100"/>
            <Connect in="103" to="13" out="100"/>
        </Operator>
        <Operator id="11" type="DFE4B30E">
            <Connect in="100" constant="-37"/>
            <Connect in="101" to="12" out="100"/>
            <Connect in="102" constant="-39"/>
            <Connect in="103" to="16" out="100"/>
        </Operator>
        <Operator id="12" type="D729EF5D">
            <Connect in="100" input="1"/>
            <Connect in="101" constant="-42"/>
            <Connect in="102" constant="-43"/>
            <Connect in="103" constant="-44"/>
            <Connect in="104" constant="-45"/>
        </Operator>
        <Operator id="13" type="B4A997AD">
            <Connect in="100" to="11" out="100"/>
            <Connect in="101" constant="-62"/>
            <Connect in="102" constant="-48"/>
            <Connect in="103" to="26" out="1"/>
        </Operator>
        <Operator id="16" type="0AEB96F3">
            <Connect in="100" constant="-54"/>
        </Operator>
        <Operator id="19" type="FA711A4D">
            <Connect in="1" input="1"/>
            <Connect in="2" to="11" out="101"/>
            <Connect in="3" constant="-145"/>
            <Connect in="4" constant="-146"/>
            <Connect in="5" constant="-147"/>
        </Operator>
        <Operator id="20" type="FA76F6CE">
            <Connect in="1" input="1"/>
            <Connect in="2" to="11" out="101"/>
            <Connect in="3" constant="-67"/>
            <Connect in="5" constant="-142"/>
            <Connect in="6" constant="-148"/>
        </Operator>
        <Operator id="21" type="FA5C48B1">
            <Connect in="1" input="1"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-150"/>
        </Operator>
        <Operator id="22" type="FA2B2EE7">
            <Connect in="1" input="1"/>
            <Connect in="2" constant="-74"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-75"/>
            <Connect in="5" constant="-127"/>
            <Connect in="6" constant="-138"/>
            <Connect in="7" constant="-155"/>
        </Operator>
        <Operator id="23" type="FA2B2EE7">
            <Connect in="1" input="1"/>
            <Connect in="2" constant="-77"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-78"/>
            <Connect in="5" constant="-128"/>
            <Connect in="6" constant="-139"/>
            <Connect in="7" constant="-156"/>
        </Operator>
        <Operator id="25" type="B4A997AD">
            <Connect in="100" to="22" out="1"/>
            <Connect in="101" to="23" out="1"/>
            <Connect in="102" to="27" out="1"/>
            <Connect in="103" to="29" out="1"/>
        </Operator>
        <Operator id="26" type="FA123505">
            <Connect in="1" input="2"/>
            <Connect in="2" to="19" out="1"/>
            <Connect in="3" to="20" out="1"/>
            <Connect in="4" to="31" out="1"/>
            <Connect in="5" to="21" out="1"/>
            <Connect in="6" to="25" out="100"/>
            <Connect in="7" to="34" out="100"/>
            <Connect in="8" constant="-95"/>
            <Connect in="9" constant="-96"/>
        </Operator>
        <Operator id="27" type="FA2B2EE7">
            <Connect in="1" input="1"/>
            <Connect in="2" constant="-97"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-98"/>
            <Connect in="5" constant="-129"/>
            <Connect in="6" constant="-140"/>
            <Connect in="7" constant="-157"/>
        </Operator>
        <Operator id="29" type="FA2B2EE7">
            <Connect in="1" input="1"/>
            <Connect in="2" constant="-101"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-102"/>
            <Connect in="5" constant="-130"/>
            <Connect in="6" constant="-141"/>
            <Connect in="7" constant="-158"/>
        </Operator>
        <Operator id="31" type="FA76F6CE">
            <Connect in="1" input="1"/>
            <Connect in="2" to="11" out="101"/>
            <Connect in="3" constant="-107"/>
            <Connect in="5" constant="-143"/>
            <Connect in="6" constant="-149"/>
        </Operator>
        <Operator id="32" type="FBEFF068">
            <Connect in="1" to="12" out="100"/>
            <Connect in="2" constant="-144"/>
        </Operator>
        <Operator id="33" type="FBA947FF">
            <Connect in="1" input="1"/>
            <Connect in="2" constant="-110"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-121"/>
            <Connect in="5" constant="-134"/>
            <Connect in="6" constant="-151"/>
        </Operator>
        <Operator id="34" type="B4A997AD">
            <Connect in="100" to="33" out="1"/>
            <Connect in="101" to="37" out="1"/>
            <Connect in="102" to="35" out="1"/>
            <Connect in="103" to="38" out="1"/>
        </Operator>
        <Operator id="35" type="FBA947FF">
            <Connect in="1" input="1"/>
            <Connect in="2" constant="-117"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-122"/>
            <Connect in="5" constant="-135"/>
            <Connect in="6" constant="-152"/>
        </Operator>
        <Operator id="37" type="FBA947FF">
            <Connect in="1" input="1"/>
            <Connect in="2" constant="-123"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-124"/>
            <Connect in="5" constant="-136"/>
            <Connect in="6" constant="-153"/>
        </Operator>
        <Operator id="38" type="FBA947FF">
            <Connect in="1" input="1"/>
            <Connect in="2" constant="-125"/>
            <Connect in="3" to="11" out="101"/>
            <Connect in="4" constant="-126"/>
            <Connect in="5" constant="-137"/>
            <Connect in="6" constant="-154"/>
        </Operator>
    </Operators>
    <Outputs>
        <Output id="1" type="ModelSegment" name="Out" description="" to="10" out="100"/>
    </Outputs>
</Procedure>
